name: admin

services:

  admin-web-app:
    build:
      dockerfile: Dockerfile
      context: .
      additional_contexts:
        - src-admin-app=../app
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_URL=${MINIO_URL}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_QUEUE_CATEGORY__NAME=${RABBITMQ_QUEUE_CATEGORY__NAME}
    ports:
      - "${DOCKER_ADMIN_APPLICATION_EXPOSE_PORT}:8080"
networks:
  default:
    name: deye-web-network
    external: true
