FROM maven:3.9.4-eclipse-temurin-17 AS build

WORKDIR /app

COPY --from=src-admin-app pom.xml ./
COPY --from=src-admin-app src ./src

RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=build /app/target/admin-app-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
