version: "3.8"

services:

  nginx:
    image: nginx:1.24-alpine
    hostname: nginx
    ports:
      - '${DOCKER_NGINX_EXPOSE_PORT_HTTP}:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/tmp/nginx_cache
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: "500M"
        reservations:
          cpus: "0.25"
          memory: "256M"
      placement:
        constraints:
          - node.role == worker

networks:
  default:
    name: deye-web-prod-network
    external: true

volumes:
  nginx_cache:
