global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: order-app
    metrics_path: /metrics/
    static_configs:
      - targets: [ "order-backend-app:8020" ]

  - job_name: catalog-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["catalog-backend-app:8080"]