version: "3.8"

services:

  iac-backend-app:
    image: startupcorp/iac-backend-app:latest
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}
      - JWT_REFRESH_TOKEN_EXPIRATION_DAYS=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "500M"
        reservations:
          cpus: "0.25"
          memory: "256M"
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

networks:
  default:
    name: deye-web-prod-network
    external: true
