{
 "title": "Catalog Microservice",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Successful Http Requests Count ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"catalog-app\", uri!=\"/actuator/prometheus\", outcome=\"SUCCESS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Http Requests Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"catalog-app\", uri!=\"/actuator/prometheus\", outcome=\"CLIENT_ERROR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Http Response Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, uri) (\n  rate(http_server_requests_seconds_sum[5m]) /\n  rate(http_server_requests_seconds_count[5m])\n)\n* 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"catalog-app\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\", job=\"catalog-app\"})) / sum(jvm_memory_max_bytes{area=\"heap\", job=\"catalog-app\"})  * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}