{
 "title": "Order Microservice",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Sent Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(path, status_code, method) (round(increase(requests_total[$__range])) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Errors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (method, path, status_code) (increase(requests_total{status_code=~\"5..\"}[$__range])) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(request_duration_sum[$__rate_interval]) / rate(request_duration_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "system_usage{resource_type='Memory'} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "system_usage{resource_type='CPU'}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}