version: '3.9'
name: customer

x-app-setup: &app-setup
  image: 'customer-app:latest'
  build:
    args:
      GROUP_ID: "${DOCKER_CUSTOMER_IMAGE_GROUP_ID}"
      USER_ID: "${DOCKER_CUSTOMER_IMAGE_USER_ID}"
    dockerfile: Dockerfile
    context: .
    additional_contexts:
      - src-customer-app=../app
  environment:
    APPLICATION_TITLE: ${APPLICATION_TITLE}
    APPLICATION_DEBUG: ${APPLICATION_DEBUG}
    APPLICATION_VERSION: ${APPLICATION_VERSION}

    DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_PORT: ${DATABASE_PORT}
    DATABASE_DATABASE: ${DATABASE_DATABASE}
    DATABASE_USERNAME: ${DATABASE_USERNAME}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}

    RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
    RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    RABBITMQ_HOST: ${RABBITMQ_HOST}
    RABBITMQ_PORT: ${RABBITMQ_PORT}

    RABBITMQ_QUEUE_CATEGORY__NAME: ${RABBITMQ_QUEUE_CATEGORY__NAME}
    RABBITMQ_QUEUE_CATEGORY__DURABLE: ${RABBITMQ_QUEUE_CATEGORY__DURABLE}
  volumes:
    - ../app/src:/app

services:

  web-app:
    <<: *app-setup
    ports:
      - '${DOCKER_CUSTOMER_APPLICATION_EXPOSE_PORT}:${CUSTOMER_APPLICATION_PORT}'
    entrypoint: [
      "uvicorn", "interface.web.app:web_app",
      "--host", "0.0.0.0",
      "--port", "${CUSTOMER_APPLICATION_PORT}",
      "--factory",
      "--reload",
    ]

  category-queue-consumer:
    <<: *app-setup
    entrypoint: [
      "faststream", "run",
      "--reload",
      "--factory",
      "interface.queue.app:queue_app",
    ]
    depends_on:
      migration-service:
        condition: service_completed_successfully

  migration-service:
    <<: *app-setup
    command: sh -c 'cd infrastructure/database/relational/migrations && alembic upgrade head'

  asyncapi-docs:
    <<: *app-setup
    entrypoint: [
      "faststream", "docs", "serve",
      "--host", "0.0.0.0",
      "--port", "${ASYNCAPI_DOCS_PORT}",
      "--reload",
      "--factory",
      "interface.queue.app:queue_app",
    ]
    ports:
      - "${DOCKER_ASYNCAPI_EXPOSE_PORT}:${ASYNCAPI_DOCS_PORT}"


networks:
  default:
    name: deye-web-network
    external: true