name: order

x-app-setup: &app-setup
  image: 'order-app:latest'
  build:
    args:
      GROUP_ID: "${DOCKER_ORDER_IMAGE_GROUP_ID}"
      USER_ID: "${DOCKER_ORDER_IMAGE_USER_ID}"
    dockerfile: Dockerfile
    context: .
    additional_contexts:
      - src-order-app=../app
  environment: &app-env
    APPLICATION_TITLE: ${APPLICATION_TITLE}
    APPLICATION_DEBUG: ${APPLICATION_DEBUG}
    APPLICATION_VERSION: ${APPLICATION_VERSION}

    DATABASE_USERNAME: ${DATABASE_USERNAME}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_PORT: ${DATABASE_PORT}
    DATABASE_DATABASE: ${DATABASE_DATABASE}

    RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
    RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    RABBITMQ_HOST: ${RABBITMQ_HOST}
    RABBITMQ_PORT: ${RABBITMQ_PORT}
  volumes:
    - ../app/src:/app

services:

  order-web-app:
    <<: *app-setup
    ports:
      - '${DOCKER_ORDER_APPLICATION_EXPOSE_PORT}:${ORDER_APPLICATION_PORT}'
    entrypoint: [
      "uvicorn", "interface.web.app:web_app",
      "--host", "0.0.0.0",
      "--port", "${ORDER_APPLICATION_PORT}",
      "--factory",
      "--reload",
    ]
    depends_on:
      migration-service:
        condition: service_completed_successfully

  queue-consumer:
    <<: *app-setup
    entrypoint: [
      "faststream", "run",
      "--factory",
      "interface.queue.app:queue_app",
    ]
    environment:
      <<: *app-env
      RABBITMQ_ORDER_QUEUE: ${RABBITMQ_ORDER_QUEUE}
    depends_on:
      migration-service:
        condition: service_completed_successfully

  migration-service:
    <<: *app-setup
    working_dir: /app/infrastructure/database/relational/migrations

networks:
  default:
    name: deye-web-network
    external: true
