name: comment

x-app-setup: &app-setup
  build: &app-build
    args:
      GROUP_ID: "${DOCKER_COMMENT_IMAGE_GROUP_ID}"
      USER_ID: "${DOCKER_COMMENT_IMAGE_USER_ID}"
      INSTALL_LOCAL_SHARED_KERNEL: "${DOCKER_INSTALL_LOCAL_SHARED_KERNEL}"
    dockerfile: Dockerfile
    context: .
    additional_contexts:
      - comment-app=../app
      - shared-kernel=../../dw_shared_kernel
  environment: &app-env
    APPLICATION_TITLE: ${APPLICATION_TITLE}
    APPLICATION_DEBUG: ${APPLICATION_DEBUG}
    APPLICATION_VERSION: ${APPLICATION_VERSION}

    DATABASE_USERNAME: ${DATABASE_USERNAME}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_PORT: ${DATABASE_PORT}
    DATABASE_DATABASE: ${DATABASE_DATABASE}

    RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
    RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    RABBITMQ_HOST: ${RABBITMQ_HOST}
    RABBITMQ_PORT: ${RABBITMQ_PORT}
  volumes:
    - ../app/src:/app

services:

  comment-web-app:
    <<: *app-setup
    image: startupcorp/comment-backend-app
    container_name: comment-backend-app
    build:
      <<: *app-build
      target: backend-app
    environment:
      <<: *app-env
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
    ports:
      - '${DOCKER_COMMENT_APPLICATION_EXPOSE_PORT}:${COMMENT_APPLICATION_PORT}'
    entrypoint: [
      "uvicorn", "interface.web.app:web_app",
      "--host", "0.0.0.0",
      "--port", "${COMMENT_APPLICATION_PORT}",
      "--factory",
      "--reload",
      "--reload-dir", ".",
    ]
    depends_on:
      comment-migration-service:
        condition: service_completed_successfully

  comment-queue-consumer:
    <<: *app-setup
    image: startupcorp/comment-queue-consumer
    container_name: comment-queue-consumer
    build:
      <<: *app-build
      target: queue-consumer
    entrypoint: [
      "faststream", "run",
      "--factory",
      "interface.queue.app:queue_app",
    ]
    environment:
      <<: *app-env
      RABBITMQ_COMMENT_PRODUCT_QUEUE: "${RABBITMQ_COMMENT_PRODUCT_QUEUE}"
    depends_on:
      comment-migration-service:
        condition: service_completed_successfully

  comment-migration-service:
    <<: *app-setup
    image: startupcorp/comment-migration-service
    container_name: comment-migration-service
    build:
      <<: *app-build
      target: migration-service
    command: [ "alembic", "upgrade", "head" ]

networks:
  default:
    name: deye-web-network
    external: true
